package com.qvc.survivors.model.upgrade;

public enum StatModifier {
   DRONE_COUNT,
   PACKAGE_VELOCITY,
   MAX_HEALTH,
   CRITICAL_CHANCE,
   PACKAGE_DAMAGE,
   PICKUP_RANGE,
   PACKAGE_CAPACITY,
   FIRE_RATE,
   DELIVERY_SPEED,
   MOVEMENT_SPEED,
   AOE_RADIUS,
   XP_BONUS,
   MONEY_BONUS,
   LIFESTEAL,
   CRIT_DAMAGE,
   DAMAGE_REDUCTION,
   PROJECTILE_COUNT;
}
